server:
  port: 8080

spring:
  sql:
    init:
      mode: never
  application:
    name: spring-boot-rest-api-mssql
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.SQLServerDialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: HCVbd4_prv@
    url:  jdbc:sqlserver://localhost:1433;databaseName=bookdb;encrypt=false
    hikari:
      poolName: Hikari
      auto-commit: false
